apiVersion: v1
kind: Service
metadata:
  name: {{ include "oda-metrics.fullname" . }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '{{ .Values.service.port }}'
  labels:
    {{- include "oda-metrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "oda-metrics.selectorLabels" . | nindent 4 }}
